name: Bug report
description: Create a report to help us address issues you are facing
title: "[Bug] "
labels: [bug]
body:
  - type: checkboxes
    id: confirmations
    attributes:
      label: ⠀
      options:
        - label: Tried latest version
          required: true
        - label: This issue is not duplicated with any other open or closed issues
          required: true

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to make the Smoking Tracker application better!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: |
        The application crashes everytime it tries to download data
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug
      placeholder: |
        1. Install the application on an older Android device (e.g. Android 8)
        2. Trigger a file download
        3. The application crashes
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: |
        The app downloads data without any problems
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Device information
      description: Provide details about your system environment
      placeholder: |
        Device:
        System:
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add them to help explain your problem
      placeholder: |
        application_screen.jpg
        crashed_screen.jpg
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: |
        Crash report:
    validations:
      required: false