default_platform(:android)

platform :android do
  lane :playstore do
    upload_to_play_store(
      package_name: "com.gasperpintar.smokingtracker",
      json_key: ENV["GOOGLE_PLAY_JSON"],
      track: "production",
      metadata_path: '/tmp/gplay_metadata',
      changes_not_sent_for_review: true
    )
  end
end