default_platform(:android)

platform :android do
  lane :playstore do
    upload_to_play_store(
      json_key: ENV["GOOGLE_PLAY_JSON"],
      track: "production",
      metadata_path: '/tmp/gplay_metadata',
      skip_submission: true
    )
  end
end