name: Sync Bots

on:
  push:
    branches: [master]

jobs:
  update-bot-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v7

      - name: Update and approve PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PRS=$(gh pr list --state open --json number,author --jq '
            .[] | select(
              .author.login == "app/dependabot" or
              .author.login == "app/github-actions" or
              .author.login == "github-actions[bot]" or
              .author.login == "weblate-translations[bot]"
            ) | .number
          ')

          [ -z "$PRS" ] && echo "No matching Pull Requests." && exit 0

          for PR in $PRS; do
            echo "Updating and approving Pull Request #$PR..."
            gh pr update-branch "$PR" || echo "Update failed."
            gh pr review "$PR" --approve || echo "Approval failed."
          done